name: bootstrap
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.4.4
  flutter_styled_toast: ^2.3.0
  flutter_svg: ^2.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  image_picker: ^1.1.2
  just_audio: ^0.9.46
  loader_overlay: ^4.0.4+1
  logarte: ^1.4.0
  logger: ^1.4.0
  package_info_plus: ^9.0.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

